In [1]:
import requests
repond=requests.get('https://oqmd.org/oqmdapi/formationenergy?fields=name,entry_id,spacegroup,ntypes,band_gap,delta_e&filter=element_set=(Mn-Fe),S')
txt=repond.json()
print(type(txt))
print(txt)

<class 'dict'>
{'links': {'next': 'http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3D%28Mn-Fe%29%2CS&limit=50&offset=50', 'previous': None, 'base_url': {'href': 'https://oqmd.org/oqmdapi', 'meta': {'_oqmd_version': '1.0'}}}, 'resource': {}, 'data': [{'name': 'FeAgAsS3', 'entry_id': 1742211, 'spacegroup': 'Cc', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.2716503474233451}, {'name': 'MnAgAsS3', 'entry_id': 1742213, 'spacegroup': 'Cc', 'ntypes': 4, 'band_gap': 0.9630000000000001, 'delta_e': -0.40002112722219546}, {'name': 'Fe2AgAuS4', 'entry_id': 1969136, 'spacegroup': 'P-6m2', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.4033197854441788}, {'name': 'BaFeAgS3', 'entry_id': 1351079, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.764094444090012}, {'name': 'BaFeAgS3', 'entry_id': 1835815, 'spacegroup': 'P21/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8278284815900125}, {'name': 'BaFeAgS3', 'entry_id': 1837608, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8358896686733459}, {'name': 'BaMnAgS3', 'entry_id': 1848577, 'spacegroup': 'P21/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -1.0048778888888623}, {'name': 'Ba2MnAgS6', 'entry_id': 1261015, 'spacegroup': 'Fm-3m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.855417966537325}, {'name': 'MnAgSBr', 'entry_id': 1769682, 'spacegroup': 'Pmma', 'ntypes': 4, 'band_gap': 0.6930000000000001, 'delta_e': -0.5135158575555732}, {'name': 'CaFeAgS3', 'entry_id': 1350935, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.724368360756679}, {'name': 'Cd2FeAgS4', 'entry_id': 1769203, 'spacegroup': 'Pmn21', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.5404612154441786}, {'name': 'MnCd2AgS4', 'entry_id': 1769213, 'spacegroup': 'Pmn21', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.6007725721683164}, {'name': 'MnAgS2Cl', 'entry_id': 1770683, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.527300928487788}, {'name': 'CsFeAgSe2S', 'entry_id': 1302259, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.329381606918893}, {'name': 'CsFeAgTe2S', 'entry_id': 1302261, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230022215530003}, {'name': 'CsFeAgSeS2', 'entry_id': 1302257, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.394618080921119}, {'name': 'CsFeAgTeS2', 'entry_id': 1302258, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.375250961476674}, {'name': 'CsFeAgS3', 'entry_id': 1254445, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.421604442423346}, {'name': 'CsMnAgSe2S', 'entry_id': 1302253, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.507246627551076}, {'name': 'CsMnAgTe2S', 'entry_id': 1302255, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.384505309495519}, {'name': 'CsMnAgSeS2', 'entry_id': 1302251, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.574319879886636}, {'name': 'CsMnAgTeS2', 'entry_id': 1302252, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.56940200044219}, {'name': 'CsMnAgS3', 'entry_id': 1254442, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.611018952222196}, {'name': 'CsMnAgS3', 'entry_id': 1847080, 'spacegroup': 'P21/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.6955201505555285}, {'name': 'EuFeAgS3', 'entry_id': 1351367, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8263010490900117}, {'name': 'EuFeAgS3', 'entry_id': 1835838, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.894365074923345}, {'name': 'EuMn2AgS2O2', 'entry_id': 1866138, 'spacegroup': 'P3m1', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -1.5040980364634944}, {'name': 'FeAgSO4F', 'entry_id': 1814880, 'spacegroup': 'P-1', 'ntypes': 5, 'band_gap': 2.112, 'delta_e': -1.6308562340717154}, {'name': 'FeAgGeS3', 'entry_id': 1351151, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.346873213256679}, {'name': 'FeAgSI', 'entry_id': 1816530, 'spacegroup': 'P212121', 'ntypes': 4, 'band_gap': 0.2469999999999999, 'delta_e': -0.1760090803604193}, {'name': 'InFeAgSe2S', 'entry_id': 1302727, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230209696085559}, {'name': 'InFeAgTe2S', 'entry_id': 1302729, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.0257937596966696}, {'name': 'InFeAgSeS2', 'entry_id': 1302725, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.298717356754453}, {'name': 'InFeAgTeS2', 'entry_id': 1302726, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.240144403976675}, {'name': 'InFeAgS3', 'entry_id': 1254670, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.357073833256679}, {'name': 'KFeAgSe2S', 'entry_id': 1301323, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.332664887752227}, {'name': 'KFeAgTe2S', 'entry_id': 1301325, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230393202196669}, {'name': 'KFeAgSeS2', 'entry_id': 1301321, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.398313917587786}, {'name': 'KFeAgTeS2', 'entry_id': 1301322, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.378438938143341}, {'name': 'KFeAgS3', 'entry_id': 1253995, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.431521720756678}, {'name': 'LiFeAgSe2S', 'entry_id': 1300387, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.298460757752226}, {'name': 'LiFeAgTe2S', 'entry_id': 1300389, 'spacegroup': 'C2/m', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.247503348863336}, {'name': 'LiFeAgSeS2', 'entry_id': 1300385, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.383124760087786}, {'name': 'LiFeAgTeS2', 'entry_id': 1300386, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.340523681476675}, {'name': 'LiFeAgS3', 'entry_id': 1253545, 'spacegroup': 'C2/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.423306621590012}, {'name': 'MgFeAgS3', 'entry_id': 1350863, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.50049405561779}, {'name': 'NaFeAgSe2S', 'entry_id': 1300855, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.2847245287275}, {'name': 'NaFeAgTe2S', 'entry_id': 1300857, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.210253226505277}, {'name': 'NaFeAgSeS2', 'entry_id': 1300853, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.369777656896394}, {'name': 'NaFeAgTeS2', 'entry_id': 1300854, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.355511549951949}], 'meta': {'query': {'representation': 'http://oqmd.org/oqmdapi/formationenergy?fields=name,entry_id,spacegroup,ntypes,band_gap,delta_e&filter=element_set=(Mn-Fe),S'}, 'api_version': '1.0', 'time_stamp': '2024-04-18 08:37:28', 'data_returned': 50, 'data_available': 5483, 'comments': '', 'query_tree': '', 'more_data_available': True}, 'response_message': 'OK'}

In [2]:
len(txt)

5

In [3]:
print(txt.keys())

dict_keys(['links', 'resource', 'data', 'meta', 'response_message'])

In [4]:
print(txt['links'])

{'next': 'http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3D%28Mn-Fe%29%2CS&limit=50&offset=50', 'previous': None, 'base_url': {'href': 'https://oqmd.org/oqmdapi', 'meta': {'_oqmd_version': '1.0'}}}

In [5]:
print(txt['resource'])

{}

In [6]:
print(txt['data'])

[{'name': 'FeAgAsS3', 'entry_id': 1742211, 'spacegroup': 'Cc', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.2716503474233451}, {'name': 'MnAgAsS3', 'entry_id': 1742213, 'spacegroup': 'Cc', 'ntypes': 4, 'band_gap': 0.9630000000000001, 'delta_e': -0.40002112722219546}, {'name': 'Fe2AgAuS4', 'entry_id': 1969136, 'spacegroup': 'P-6m2', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.4033197854441788}, {'name': 'BaFeAgS3', 'entry_id': 1351079, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.764094444090012}, {'name': 'BaFeAgS3', 'entry_id': 1835815, 'spacegroup': 'P21/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8278284815900125}, {'name': 'BaFeAgS3', 'entry_id': 1837608, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8358896686733459}, {'name': 'BaMnAgS3', 'entry_id': 1848577, 'spacegroup': 'P21/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -1.0048778888888623}, {'name': 'Ba2MnAgS6', 'entry_id': 1261015, 'spacegroup': 'Fm-3m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.855417966537325}, {'name': 'MnAgSBr', 'entry_id': 1769682, 'spacegroup': 'Pmma', 'ntypes': 4, 'band_gap': 0.6930000000000001, 'delta_e': -0.5135158575555732}, {'name': 'CaFeAgS3', 'entry_id': 1350935, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.724368360756679}, {'name': 'Cd2FeAgS4', 'entry_id': 1769203, 'spacegroup': 'Pmn21', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.5404612154441786}, {'name': 'MnCd2AgS4', 'entry_id': 1769213, 'spacegroup': 'Pmn21', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.6007725721683164}, {'name': 'MnAgS2Cl', 'entry_id': 1770683, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.527300928487788}, {'name': 'CsFeAgSe2S', 'entry_id': 1302259, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.329381606918893}, {'name': 'CsFeAgTe2S', 'entry_id': 1302261, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230022215530003}, {'name': 'CsFeAgSeS2', 'entry_id': 1302257, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.394618080921119}, {'name': 'CsFeAgTeS2', 'entry_id': 1302258, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.375250961476674}, {'name': 'CsFeAgS3', 'entry_id': 1254445, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.421604442423346}, {'name': 'CsMnAgSe2S', 'entry_id': 1302253, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.507246627551076}, {'name': 'CsMnAgTe2S', 'entry_id': 1302255, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.384505309495519}, {'name': 'CsMnAgSeS2', 'entry_id': 1302251, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.574319879886636}, {'name': 'CsMnAgTeS2', 'entry_id': 1302252, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.56940200044219}, {'name': 'CsMnAgS3', 'entry_id': 1254442, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.611018952222196}, {'name': 'CsMnAgS3', 'entry_id': 1847080, 'spacegroup': 'P21/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.6955201505555285}, {'name': 'EuFeAgS3', 'entry_id': 1351367, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8263010490900117}, {'name': 'EuFeAgS3', 'entry_id': 1835838, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.894365074923345}, {'name': 'EuMn2AgS2O2', 'entry_id': 1866138, 'spacegroup': 'P3m1', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -1.5040980364634944}, {'name': 'FeAgSO4F', 'entry_id': 1814880, 'spacegroup': 'P-1', 'ntypes': 5, 'band_gap': 2.112, 'delta_e': -1.6308562340717154}, {'name': 'FeAgGeS3', 'entry_id': 1351151, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.346873213256679}, {'name': 'FeAgSI', 'entry_id': 1816530, 'spacegroup': 'P212121', 'ntypes': 4, 'band_gap': 0.2469999999999999, 'delta_e': -0.1760090803604193}, {'name': 'InFeAgSe2S', 'entry_id': 1302727, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230209696085559}, {'name': 'InFeAgTe2S', 'entry_id': 1302729, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.0257937596966696}, {'name': 'InFeAgSeS2', 'entry_id': 1302725, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.298717356754453}, {'name': 'InFeAgTeS2', 'entry_id': 1302726, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.240144403976675}, {'name': 'InFeAgS3', 'entry_id': 1254670, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.357073833256679}, {'name': 'KFeAgSe2S', 'entry_id': 1301323, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.332664887752227}, {'name': 'KFeAgTe2S', 'entry_id': 1301325, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230393202196669}, {'name': 'KFeAgSeS2', 'entry_id': 1301321, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.398313917587786}, {'name': 'KFeAgTeS2', 'entry_id': 1301322, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.378438938143341}, {'name': 'KFeAgS3', 'entry_id': 1253995, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.431521720756678}, {'name': 'LiFeAgSe2S', 'entry_id': 1300387, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.298460757752226}, {'name': 'LiFeAgTe2S', 'entry_id': 1300389, 'spacegroup': 'C2/m', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.247503348863336}, {'name': 'LiFeAgSeS2', 'entry_id': 1300385, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.383124760087786}, {'name': 'LiFeAgTeS2', 'entry_id': 1300386, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.340523681476675}, {'name': 'LiFeAgS3', 'entry_id': 1253545, 'spacegroup': 'C2/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.423306621590012}, {'name': 'MgFeAgS3', 'entry_id': 1350863, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.50049405561779}, {'name': 'NaFeAgSe2S', 'entry_id': 1300855, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.2847245287275}, {'name': 'NaFeAgTe2S', 'entry_id': 1300857, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.210253226505277}, {'name': 'NaFeAgSeS2', 'entry_id': 1300853, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.369777656896394}, {'name': 'NaFeAgTeS2', 'entry_id': 1300854, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.355511549951949}]

In [7]:
print(txt['meta'])

{'query': {'representation': 'http://oqmd.org/oqmdapi/formationenergy?fields=name,entry_id,spacegroup,ntypes,band_gap,delta_e&filter=element_set=(Mn-Fe),S'}, 'api_version': '1.0', 'time_stamp': '2024-04-18 08:37:28', 'data_returned': 50, 'data_available': 5483, 'comments': '', 'query_tree': '', 'more_data_available': True}

In [8]:
print(txt['response_message'])

OK

In [9]:
len(txt['data'])

50

In [10]:
print(txt['data'][0])

{'name': 'FeAgAsS3', 'entry_id': 1742211, 'spacegroup': 'Cc', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.2716503474233451}

In [11]:
oqmd_dict={txt['data'][i]['entry_id']:[txt['data'][i]['name'],txt['data'][i]['spacegroup'],txt['data'][i]['ntypes'],txt['data'][i]['band_gap'],txt['data'][i]['delta_e']] for i in range(len(txt['data']))}

In [12]:
print(oqmd_dict)

{1742211: ['FeAgAsS3', 'Cc', 4, 0.0, -0.2716503474233451], 1742213: ['MnAgAsS3', 'Cc', 4, 0.9630000000000001, -0.40002112722219546], 1969136: ['Fe2AgAuS4', 'P-6m2', 4, 0.0, -0.4033197854441788], 1351079: ['BaFeAgS3', 'Cmcm', 4, 0.0, -0.764094444090012], 1835815: ['BaFeAgS3', 'P21/m', 4, 0.0, -0.8278284815900125], 1837608: ['BaFeAgS3', 'Pnma', 4, 0.0, -0.8358896686733459], 1848577: ['BaMnAgS3', 'P21/m', 4, 0.0, -1.0048778888888623], 1261015: ['Ba2MnAgS6', 'Fm-3m', 4, 0.0, -0.855417966537325], 1769682: ['MnAgSBr', 'Pmma', 4, 0.6930000000000001, -0.5135158575555732], 1350935: ['CaFeAgS3', 'Cmcm', 4, 0.0, -0.724368360756679], 1769203: ['Cd2FeAgS4', 'Pmn21', 4, 0.0, -0.5404612154441786], 1769213: ['MnCd2AgS4', 'Pmn21', 4, 0.0, -0.6007725721683164], 1770683: ['MnAgS2Cl', 'Pnma', 4, 0.0, -0.527300928487788], 1302259: ['CsFeAgSe2S', 'Cmcm', 5, 0.0, -0.329381606918893], 1302261: ['CsFeAgTe2S', 'Cmcm', 5, 0.0, -0.230022215530003], 1302257: ['CsFeAgSeS2', 'Cmcm', 5, 0.0, -0.394618080921119], 1302258: ['CsFeAgTeS2', 'Cmcm', 5, 0.0, -0.375250961476674], 1254445: ['CsFeAgS3', 'Cmcm', 4, 0.0, -0.421604442423346], 1302253: ['CsMnAgSe2S', 'Cmcm', 5, 0.0, -0.507246627551076], 1302255: ['CsMnAgTe2S', 'Cmcm', 5, 0.0, -0.384505309495519], 1302251: ['CsMnAgSeS2', 'Cmcm', 5, 0.0, -0.574319879886636], 1302252: ['CsMnAgTeS2', 'Cmcm', 5, 0.0, -0.56940200044219], 1254442: ['CsMnAgS3', 'Cmcm', 4, 0.0, -0.611018952222196], 1847080: ['CsMnAgS3', 'P21/m', 4, 0.0, -0.6955201505555285], 1351367: ['EuFeAgS3', 'Cmcm', 4, 0.0, -0.8263010490900117], 1835838: ['EuFeAgS3', 'Pnma', 4, 0.0, -0.894365074923345], 1866138: ['EuMn2AgS2O2', 'P3m1', 5, 0.0, -1.5040980364634944], 1814880: ['FeAgSO4F', 'P-1', 5, 2.112, -1.6308562340717154], 1351151: ['FeAgGeS3', 'Cmcm', 4, 0.0, -0.346873213256679], 1816530: ['FeAgSI', 'P212121', 4, 0.2469999999999999, -0.1760090803604193], 1302727: ['InFeAgSe2S', 'Cmcm', 5, 0.0, -0.230209696085559], 1302729: ['InFeAgTe2S', 'Cmcm', 5, 0.0, -0.0257937596966696], 1302725: ['InFeAgSeS2', 'Cmcm', 5, 0.0, -0.298717356754453], 1302726: ['InFeAgTeS2', 'Cmcm', 5, 0.0, -0.240144403976675], 1254670: ['InFeAgS3', 'Cmcm', 4, 0.0, -0.357073833256679], 1301323: ['KFeAgSe2S', 'Cmcm', 5, 0.0, -0.332664887752227], 1301325: ['KFeAgTe2S', 'Cmcm', 5, 0.0, -0.230393202196669], 1301321: ['KFeAgSeS2', 'Cmcm', 5, 0.0, -0.398313917587786], 1301322: ['KFeAgTeS2', 'Cmcm', 5, 0.0, -0.378438938143341], 1253995: ['KFeAgS3', 'Cmcm', 4, 0.0, -0.431521720756678], 1300387: ['LiFeAgSe2S', 'Cmcm', 5, 0.0, -0.298460757752226], 1300389: ['LiFeAgTe2S', 'C2/m', 5, 0.0, -0.247503348863336], 1300385: ['LiFeAgSeS2', 'Cmcm', 5, 0.0, -0.383124760087786], 1300386: ['LiFeAgTeS2', 'Cmcm', 5, 0.0, -0.340523681476675], 1253545: ['LiFeAgS3', 'C2/m', 4, 0.0, -0.423306621590012], 1350863: ['MgFeAgS3', 'Cmcm', 4, 0.0, -0.50049405561779], 1300855: ['NaFeAgSe2S', 'Cmcm', 5, 0.0, -0.2847245287275], 1300857: ['NaFeAgTe2S', 'Cmcm', 5, 0.0, -0.210253226505277], 1300853: ['NaFeAgSeS2', 'Cmcm', 5, 0.0, -0.369777656896394], 1300854: ['NaFeAgTeS2', 'Cmcm', 5, 0.0, -0.355511549951949]}

In [13]:
import pandas as pd
df=pd.DataFrame.from_dict(oqmd_dict,orient="index")
df.head()

                 0      1  2      3         4
1742211   FeAgAsS3     Cc  4  0.000 -0.271650
1742213   MnAgAsS3     Cc  4  0.963 -0.400021
1969136  Fe2AgAuS4  P-6m2  4  0.000 -0.403320
1351079   BaFeAgS3   Cmcm  4  0.000 -0.764094
1835815   BaFeAgS3  P21/m  4  0.000 -0.827828

In [14]:
print(txt['links'])

{'next': 'http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3D%28Mn-Fe%29%2CS&limit=50&offset=50', 'previous': None, 'base_url': {'href': 'https://oqmd.org/oqmdapi', 'meta': {'_oqmd_version': '1.0'}}}

In [15]:
import requests
next='http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3D%28Mn-Fe%29%2CS&limit=50&offset=50'
repond=requests.get(next)
txt=repond.json()
print(txt)

{'links': {'next': 'http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3D%28Mn-Fe%29%2CS&limit=50&offset=100', 'previous': 'http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3D%28Mn-Fe%29%2CS&limit=50', 'base_url': {'href': 'https://oqmd.org/oqmdapi', 'meta': {'_oqmd_version': '1.0'}}}, 'resource': {}, 'data': [{'name': 'NaFeAgS3', 'entry_id': 1253770, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.409664657565287}, {'name': 'FeAgSO', 'entry_id': 1023501, 'spacegroup': 'Cmc21', 'ntypes': 4, 'band_gap': 0.206, 'delta_e': -0.492758781451588}, {'name': 'FeAgSO', 'entry_id': 1023725, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.571893011451588}, {'name': 'FeAgSO', 'entry_id': 1023780, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.225, 'delta_e': -0.563762981451589}, {'name': 'FeAgSO', 'entry_id': 1023446, 'spacegroup': 'P1', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.651989830201589}, {'name': 'FeAgSO', 'entry_id': 1036759, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.673931222701588}, {'name': 'FeAgSO', 'entry_id': 1047500, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.313937075201588}, {'name': 'FeAgSO', 'entry_id': 1047617, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.240876586451589}, {'name': 'FeAgSO', 'entry_id': 1047842, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.0445543402015884}, {'name': 'FeAgSO', 'entry_id': 1047959, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.794092405201589}, {'name': 'FeAgSO', 'entry_id': 1048184, 'spacegroup': 'Abm2', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.792194415826589}, {'name': 'FeAgSO', 'entry_id': 1048301, 'spacegroup': 'Pca21', 'ntypes': 4, 'band_gap': 0.401, 'delta_e': -0.526312738326588}, {'name': 'FeAgSO', 'entry_id': 1048526, 'spacegroup': 'P212121', 'ntypes': 4, 'band_gap': 0.201, 'delta_e': -0.678279640826589}, {'name': 'FeAgSO', 'entry_id': 1048643, 'spacegroup': 'P212121', 'ntypes': 4, 'band_gap': 0.406, 'delta_e': -0.636003151451589}, {'name': 'FeAgSO', 'entry_id': 1048868, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.311510881451588}, {'name': 'FeAgSO', 'entry_id': 1048985, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.212025970201589}, {'name': 'FeAgSO', 'entry_id': 1050011, 'spacegroup': 'P21/c', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.516209193639089}, {'name': 'FeAgSO', 'entry_id': 1049894, 'spacegroup': 'Pbca', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.596899981139089}, {'name': 'FeAgSO', 'entry_id': 1101126, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.735225178951588}, {'name': 'FeAgSO', 'entry_id': 1101317, 'spacegroup': 'P21/c', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.714376253951588}, {'name': 'FeAgSO', 'entry_id': 1101507, 'spacegroup': 'Pmc21', 'ntypes': 4, 'band_gap': 0.212, 'delta_e': -0.687533520201589}, {'name': 'FeAgSO', 'entry_id': 1103334, 'spacegroup': 'Pca21', 'ntypes': 4, 'band_gap': 0.2, 'delta_e': -0.516792940201588}, {'name': 'FeAgSO', 'entry_id': 1110060, 'spacegroup': 'P21', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.653810085826589}, {'name': 'FeAgSO', 'entry_id': 1270544, 'spacegroup': 'Cmc21', 'ntypes': 4, 'band_gap': 0.212, 'delta_e': -0.675017925201589}, {'name': 'Sr2FeAgSO3', 'entry_id': 1735807, 'spacegroup': 'P4/nmm', 'ntypes': 5, 'band_gap': 0.7549999999999994, 'delta_e': -2.028880049070482}, {'name': 'FeAgPbS3', 'entry_id': 1351295, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.316075666590012}, {'name': 'RbFeAgSe2S', 'entry_id': 1301791, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.32631178358556}, {'name': 'RbFeAgTe2S', 'entry_id': 1301793, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.224054615530003}, {'name': 'RbFeAgSeS2', 'entry_id': 1301789, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.39287077592112}, {'name': 'RbFeAgTeS2', 'entry_id': 1301790, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.371019615643341}, {'name': 'RbFeAgS3', 'entry_id': 1254220, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.423401641590013}, {'name': 'TlFeAgSe2S', 'entry_id': 1303195, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.128247296918893}, {'name': 'TlFeAgTe2S', 'entry_id': 1303197, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.0225224913633362}, {'name': 'FeAgS2', 'entry_id': 10121, 'spacegroup': 'I-42d', 'ntypes': 3, 'band_gap': 0.0, 'delta_e': -0.309199323881678}, {'name': 'FeAgS2', 'entry_id': 99471, 'spacegroup': 'I-42d', 'ntypes': 3, 'band_gap': 0.0, 'delta_e': -0.309188512631678}, {'name': 'FeAgS2', 'entry_id': 1773057, 'spacegroup': 'Pna21', 'ntypes': 3, 'band_gap': 0.0, 'delta_e': -0.29232147263167896}, {'name': 'TlFeAgSeS2', 'entry_id': 1303193, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.240556057587786}, {'name': 'TlFeAgTeS2', 'entry_id': 1303194, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.213994178976674}, {'name': 'FeAgSnS3', 'entry_id': 1351223, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.394347351898546}, {'name': 'SrFeAgS3', 'entry_id': 1351007, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.752565630756679}, {'name': 'SrFeAgS3', 'entry_id': 1836818, 'spacegroup': 'P21/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8393257674233455}, {'name': 'SrFeAgS3', 'entry_id': 1836379, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8207509278400119}, {'name': 'TlFeAgS3', 'entry_id': 1254895, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.253915751590013}, {'name': 'Fe2AgS3', 'entry_id': 12470, 'spacegroup': 'Cmca', 'ntypes': 3, 'band_gap': 0.0, 'delta_e': -0.407933019090013}, {'name': 'Fe2AgS3', 'entry_id': 21047, 'spacegroup': 'P21/c', 'ntypes': 3, 'band_gap': 0.0, 'delta_e': -0.413765360340013}, {'name': 'Fe2AgS3', 'entry_id': 671448, 'spacegroup': 'Cmca', 'ntypes': 3, 'band_gap': 0.0, 'delta_e': -0.409521880756679}, {'name': 'Fe3AgS5', 'entry_id': 1891598, 'spacegroup': 'P6/mmm', 'ntypes': 3, 'band_gap': 0.0, 'delta_e': -0.19067524195186536}, {'name': 'Mn2GaAgS4', 'entry_id': 1769205, 'spacegroup': 'Pmn21', 'ntypes': 4, 'band_gap': 0.5169999999999999, 'delta_e': -0.6813644220174533}, {'name': 'GdMnAgS3', 'entry_id': 1850278, 'spacegroup': 'P21/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -1.0200494076388622}, {'name': 'MnAgSI', 'entry_id': 1769671, 'spacegroup': 'Pmma', 'ntypes': 4, 'band_gap': 0.7770000000000001, 'delta_e': -0.3860034844336937}], 'meta': {'query': {'representation': 'http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3D%28Mn-Fe%29%2CS&limit=50&offset=50'}, 'api_version': '1.0', 'time_stamp': '2024-04-18 08:58:38', 'data_returned': 50, 'data_available': 5483, 'comments': '', 'query_tree': '', 'more_data_available': True}, 'response_message': 'OK'}

In [16]:
import requests
get_data=[]
repond=requests.get('https://oqmd.org/oqmdapi/formationenergy?fields=name,entry_id,spacegroup,ntypes,band_gap,delta_e&filter=element_set=Fe,S')
txt=repond.json()
for i in txt['data']:
    get_data.append(i)
    print(i)
print(txt)
print(get_data)
print(len(get_data))

{'name': 'FeAgAsS3', 'entry_id': 1742211, 'spacegroup': 'Cc', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.2716503474233451}
{'name': 'Fe2AgAuS4', 'entry_id': 1969136, 'spacegroup': 'P-6m2', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.4033197854441788}
{'name': 'BaFeAgS3', 'entry_id': 1351079, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.764094444090012}
{'name': 'BaFeAgS3', 'entry_id': 1835815, 'spacegroup': 'P21/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8278284815900125}
{'name': 'BaFeAgS3', 'entry_id': 1837608, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8358896686733459}
{'name': 'CaFeAgS3', 'entry_id': 1350935, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.724368360756679}
{'name': 'Cd2FeAgS4', 'entry_id': 1769203, 'spacegroup': 'Pmn21', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.5404612154441786}
{'name': 'CsFeAgSe2S', 'entry_id': 1302259, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.329381606918893}
{'name': 'CsFeAgTe2S', 'entry_id': 1302261, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230022215530003}
{'name': 'CsFeAgSeS2', 'entry_id': 1302257, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.394618080921119}
{'name': 'CsFeAgTeS2', 'entry_id': 1302258, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.375250961476674}
{'name': 'CsFeAgS3', 'entry_id': 1254445, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.421604442423346}
{'name': 'EuFeAgS3', 'entry_id': 1351367, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8263010490900117}
{'name': 'EuFeAgS3', 'entry_id': 1835838, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.894365074923345}
{'name': 'FeAgSO4F', 'entry_id': 1814880, 'spacegroup': 'P-1', 'ntypes': 5, 'band_gap': 2.112, 'delta_e': -1.6308562340717154}
{'name': 'FeAgGeS3', 'entry_id': 1351151, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.346873213256679}
{'name': 'FeAgSI', 'entry_id': 1816530, 'spacegroup': 'P212121', 'ntypes': 4, 'band_gap': 0.2469999999999999, 'delta_e': -0.1760090803604193}
{'name': 'InFeAgSe2S', 'entry_id': 1302727, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230209696085559}
{'name': 'InFeAgTe2S', 'entry_id': 1302729, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.0257937596966696}
{'name': 'InFeAgSeS2', 'entry_id': 1302725, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.298717356754453}
{'name': 'InFeAgTeS2', 'entry_id': 1302726, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.240144403976675}
{'name': 'InFeAgS3', 'entry_id': 1254670, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.357073833256679}
{'name': 'KFeAgSe2S', 'entry_id': 1301323, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.332664887752227}
{'name': 'KFeAgTe2S', 'entry_id': 1301325, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230393202196669}
{'name': 'KFeAgSeS2', 'entry_id': 1301321, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.398313917587786}
{'name': 'KFeAgTeS2', 'entry_id': 1301322, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.378438938143341}
{'name': 'KFeAgS3', 'entry_id': 1253995, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.431521720756678}
{'name': 'LiFeAgSe2S', 'entry_id': 1300387, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.298460757752226}
{'name': 'LiFeAgTe2S', 'entry_id': 1300389, 'spacegroup': 'C2/m', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.247503348863336}
{'name': 'LiFeAgSeS2', 'entry_id': 1300385, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.383124760087786}
{'name': 'LiFeAgTeS2', 'entry_id': 1300386, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.340523681476675}
{'name': 'LiFeAgS3', 'entry_id': 1253545, 'spacegroup': 'C2/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.423306621590012}
{'name': 'MgFeAgS3', 'entry_id': 1350863, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.50049405561779}
{'name': 'NaFeAgSe2S', 'entry_id': 1300855, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.2847245287275}
{'name': 'NaFeAgTe2S', 'entry_id': 1300857, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.210253226505277}
{'name': 'NaFeAgSeS2', 'entry_id': 1300853, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.369777656896394}
{'name': 'NaFeAgTeS2', 'entry_id': 1300854, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.355511549951949}
{'name': 'NaFeAgS3', 'entry_id': 1253770, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.409664657565287}
{'name': 'FeAgSO', 'entry_id': 1023501, 'spacegroup': 'Cmc21', 'ntypes': 4, 'band_gap': 0.206, 'delta_e': -0.492758781451588}
{'name': 'FeAgSO', 'entry_id': 1023725, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.571893011451588}
{'name': 'FeAgSO', 'entry_id': 1023780, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.225, 'delta_e': -0.563762981451589}
{'name': 'FeAgSO', 'entry_id': 1023446, 'spacegroup': 'P1', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.651989830201589}
{'name': 'FeAgSO', 'entry_id': 1036759, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.673931222701588}
{'name': 'FeAgSO', 'entry_id': 1047500, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.313937075201588}
{'name': 'FeAgSO', 'entry_id': 1047617, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.240876586451589}
{'name': 'FeAgSO', 'entry_id': 1047842, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.0445543402015884}
{'name': 'FeAgSO', 'entry_id': 1047959, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.794092405201589}
{'name': 'FeAgSO', 'entry_id': 1048184, 'spacegroup': 'Abm2', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.792194415826589}
{'name': 'FeAgSO', 'entry_id': 1048301, 'spacegroup': 'Pca21', 'ntypes': 4, 'band_gap': 0.401, 'delta_e': -0.526312738326588}
{'name': 'FeAgSO', 'entry_id': 1048526, 'spacegroup': 'P212121', 'ntypes': 4, 'band_gap': 0.201, 'delta_e': -0.678279640826589}
{'links': {'next': 'http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=50', 'previous': None, 'base_url': {'href': 'https://oqmd.org/oqmdapi', 'meta': {'_oqmd_version': '1.0'}}}, 'resource': {}, 'data': [{'name': 'FeAgAsS3', 'entry_id': 1742211, 'spacegroup': 'Cc', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.2716503474233451}, {'name': 'Fe2AgAuS4', 'entry_id': 1969136, 'spacegroup': 'P-6m2', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.4033197854441788}, {'name': 'BaFeAgS3', 'entry_id': 1351079, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.764094444090012}, {'name': 'BaFeAgS3', 'entry_id': 1835815, 'spacegroup': 'P21/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8278284815900125}, {'name': 'BaFeAgS3', 'entry_id': 1837608, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8358896686733459}, {'name': 'CaFeAgS3', 'entry_id': 1350935, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.724368360756679}, {'name': 'Cd2FeAgS4', 'entry_id': 1769203, 'spacegroup': 'Pmn21', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.5404612154441786}, {'name': 'CsFeAgSe2S', 'entry_id': 1302259, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.329381606918893}, {'name': 'CsFeAgTe2S', 'entry_id': 1302261, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230022215530003}, {'name': 'CsFeAgSeS2', 'entry_id': 1302257, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.394618080921119}, {'name': 'CsFeAgTeS2', 'entry_id': 1302258, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.375250961476674}, {'name': 'CsFeAgS3', 'entry_id': 1254445, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.421604442423346}, {'name': 'EuFeAgS3', 'entry_id': 1351367, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8263010490900117}, {'name': 'EuFeAgS3', 'entry_id': 1835838, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.894365074923345}, {'name': 'FeAgSO4F', 'entry_id': 1814880, 'spacegroup': 'P-1', 'ntypes': 5, 'band_gap': 2.112, 'delta_e': -1.6308562340717154}, {'name': 'FeAgGeS3', 'entry_id': 1351151, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.346873213256679}, {'name': 'FeAgSI', 'entry_id': 1816530, 'spacegroup': 'P212121', 'ntypes': 4, 'band_gap': 0.2469999999999999, 'delta_e': -0.1760090803604193}, {'name': 'InFeAgSe2S', 'entry_id': 1302727, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230209696085559}, {'name': 'InFeAgTe2S', 'entry_id': 1302729, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.0257937596966696}, {'name': 'InFeAgSeS2', 'entry_id': 1302725, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.298717356754453}, {'name': 'InFeAgTeS2', 'entry_id': 1302726, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.240144403976675}, {'name': 'InFeAgS3', 'entry_id': 1254670, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.357073833256679}, {'name': 'KFeAgSe2S', 'entry_id': 1301323, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.332664887752227}, {'name': 'KFeAgTe2S', 'entry_id': 1301325, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230393202196669}, {'name': 'KFeAgSeS2', 'entry_id': 1301321, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.398313917587786}, {'name': 'KFeAgTeS2', 'entry_id': 1301322, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.378438938143341}, {'name': 'KFeAgS3', 'entry_id': 1253995, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.431521720756678}, {'name': 'LiFeAgSe2S', 'entry_id': 1300387, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.298460757752226}, {'name': 'LiFeAgTe2S', 'entry_id': 1300389, 'spacegroup': 'C2/m', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.247503348863336}, {'name': 'LiFeAgSeS2', 'entry_id': 1300385, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.383124760087786}, {'name': 'LiFeAgTeS2', 'entry_id': 1300386, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.340523681476675}, {'name': 'LiFeAgS3', 'entry_id': 1253545, 'spacegroup': 'C2/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.423306621590012}, {'name': 'MgFeAgS3', 'entry_id': 1350863, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.50049405561779}, {'name': 'NaFeAgSe2S', 'entry_id': 1300855, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.2847245287275}, {'name': 'NaFeAgTe2S', 'entry_id': 1300857, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.210253226505277}, {'name': 'NaFeAgSeS2', 'entry_id': 1300853, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.369777656896394}, {'name': 'NaFeAgTeS2', 'entry_id': 1300854, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.355511549951949}, {'name': 'NaFeAgS3', 'entry_id': 1253770, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.409664657565287}, {'name': 'FeAgSO', 'entry_id': 1023501, 'spacegroup': 'Cmc21', 'ntypes': 4, 'band_gap': 0.206, 'delta_e': -0.492758781451588}, {'name': 'FeAgSO', 'entry_id': 1023725, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.571893011451588}, {'name': 'FeAgSO', 'entry_id': 1023780, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.225, 'delta_e': -0.563762981451589}, {'name': 'FeAgSO', 'entry_id': 1023446, 'spacegroup': 'P1', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.651989830201589}, {'name': 'FeAgSO', 'entry_id': 1036759, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.673931222701588}, {'name': 'FeAgSO', 'entry_id': 1047500, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.313937075201588}, {'name': 'FeAgSO', 'entry_id': 1047617, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.240876586451589}, {'name': 'FeAgSO', 'entry_id': 1047842, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.0445543402015884}, {'name': 'FeAgSO', 'entry_id': 1047959, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.794092405201589}, {'name': 'FeAgSO', 'entry_id': 1048184, 'spacegroup': 'Abm2', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.792194415826589}, {'name': 'FeAgSO', 'entry_id': 1048301, 'spacegroup': 'Pca21', 'ntypes': 4, 'band_gap': 0.401, 'delta_e': -0.526312738326588}, {'name': 'FeAgSO', 'entry_id': 1048526, 'spacegroup': 'P212121', 'ntypes': 4, 'band_gap': 0.201, 'delta_e': -0.678279640826589}], 'meta': {'query': {'representation': 'http://oqmd.org/oqmdapi/formationenergy?fields=name,entry_id,spacegroup,ntypes,band_gap,delta_e&filter=element_set=Fe,S'}, 'api_version': '1.0', 'time_stamp': '2024-04-18 09:00:21', 'data_returned': 50, 'data_available': 2244, 'comments': '', 'query_tree': '', 'more_data_available': True}, 'response_message': 'OK'}
[{'name': 'FeAgAsS3', 'entry_id': 1742211, 'spacegroup': 'Cc', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.2716503474233451}, {'name': 'Fe2AgAuS4', 'entry_id': 1969136, 'spacegroup': 'P-6m2', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.4033197854441788}, {'name': 'BaFeAgS3', 'entry_id': 1351079, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.764094444090012}, {'name': 'BaFeAgS3', 'entry_id': 1835815, 'spacegroup': 'P21/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8278284815900125}, {'name': 'BaFeAgS3', 'entry_id': 1837608, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8358896686733459}, {'name': 'CaFeAgS3', 'entry_id': 1350935, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.724368360756679}, {'name': 'Cd2FeAgS4', 'entry_id': 1769203, 'spacegroup': 'Pmn21', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.5404612154441786}, {'name': 'CsFeAgSe2S', 'entry_id': 1302259, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.329381606918893}, {'name': 'CsFeAgTe2S', 'entry_id': 1302261, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230022215530003}, {'name': 'CsFeAgSeS2', 'entry_id': 1302257, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.394618080921119}, {'name': 'CsFeAgTeS2', 'entry_id': 1302258, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.375250961476674}, {'name': 'CsFeAgS3', 'entry_id': 1254445, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.421604442423346}, {'name': 'EuFeAgS3', 'entry_id': 1351367, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8263010490900117}, {'name': 'EuFeAgS3', 'entry_id': 1835838, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.894365074923345}, {'name': 'FeAgSO4F', 'entry_id': 1814880, 'spacegroup': 'P-1', 'ntypes': 5, 'band_gap': 2.112, 'delta_e': -1.6308562340717154}, {'name': 'FeAgGeS3', 'entry_id': 1351151, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.346873213256679}, {'name': 'FeAgSI', 'entry_id': 1816530, 'spacegroup': 'P212121', 'ntypes': 4, 'band_gap': 0.2469999999999999, 'delta_e': -0.1760090803604193}, {'name': 'InFeAgSe2S', 'entry_id': 1302727, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230209696085559}, {'name': 'InFeAgTe2S', 'entry_id': 1302729, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.0257937596966696}, {'name': 'InFeAgSeS2', 'entry_id': 1302725, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.298717356754453}, {'name': 'InFeAgTeS2', 'entry_id': 1302726, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.240144403976675}, {'name': 'InFeAgS3', 'entry_id': 1254670, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.357073833256679}, {'name': 'KFeAgSe2S', 'entry_id': 1301323, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.332664887752227}, {'name': 'KFeAgTe2S', 'entry_id': 1301325, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230393202196669}, {'name': 'KFeAgSeS2', 'entry_id': 1301321, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.398313917587786}, {'name': 'KFeAgTeS2', 'entry_id': 1301322, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.378438938143341}, {'name': 'KFeAgS3', 'entry_id': 1253995, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.431521720756678}, {'name': 'LiFeAgSe2S', 'entry_id': 1300387, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.298460757752226}, {'name': 'LiFeAgTe2S', 'entry_id': 1300389, 'spacegroup': 'C2/m', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.247503348863336}, {'name': 'LiFeAgSeS2', 'entry_id': 1300385, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.383124760087786}, {'name': 'LiFeAgTeS2', 'entry_id': 1300386, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.340523681476675}, {'name': 'LiFeAgS3', 'entry_id': 1253545, 'spacegroup': 'C2/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.423306621590012}, {'name': 'MgFeAgS3', 'entry_id': 1350863, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.50049405561779}, {'name': 'NaFeAgSe2S', 'entry_id': 1300855, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.2847245287275}, {'name': 'NaFeAgTe2S', 'entry_id': 1300857, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.210253226505277}, {'name': 'NaFeAgSeS2', 'entry_id': 1300853, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.369777656896394}, {'name': 'NaFeAgTeS2', 'entry_id': 1300854, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.355511549951949}, {'name': 'NaFeAgS3', 'entry_id': 1253770, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.409664657565287}, {'name': 'FeAgSO', 'entry_id': 1023501, 'spacegroup': 'Cmc21', 'ntypes': 4, 'band_gap': 0.206, 'delta_e': -0.492758781451588}, {'name': 'FeAgSO', 'entry_id': 1023725, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.571893011451588}, {'name': 'FeAgSO', 'entry_id': 1023780, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.225, 'delta_e': -0.563762981451589}, {'name': 'FeAgSO', 'entry_id': 1023446, 'spacegroup': 'P1', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.651989830201589}, {'name': 'FeAgSO', 'entry_id': 1036759, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.673931222701588}, {'name': 'FeAgSO', 'entry_id': 1047500, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.313937075201588}, {'name': 'FeAgSO', 'entry_id': 1047617, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.240876586451589}, {'name': 'FeAgSO', 'entry_id': 1047842, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.0445543402015884}, {'name': 'FeAgSO', 'entry_id': 1047959, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.794092405201589}, {'name': 'FeAgSO', 'entry_id': 1048184, 'spacegroup': 'Abm2', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.792194415826589}, {'name': 'FeAgSO', 'entry_id': 1048301, 'spacegroup': 'Pca21', 'ntypes': 4, 'band_gap': 0.401, 'delta_e': -0.526312738326588}, {'name': 'FeAgSO', 'entry_id': 1048526, 'spacegroup': 'P212121', 'ntypes': 4, 'band_gap': 0.201, 'delta_e': -0.678279640826589}]
50

In [17]:
print(get_data)

[{'name': 'FeAgAsS3', 'entry_id': 1742211, 'spacegroup': 'Cc', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.2716503474233451}, {'name': 'Fe2AgAuS4', 'entry_id': 1969136, 'spacegroup': 'P-6m2', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.4033197854441788}, {'name': 'BaFeAgS3', 'entry_id': 1351079, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.764094444090012}, {'name': 'BaFeAgS3', 'entry_id': 1835815, 'spacegroup': 'P21/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8278284815900125}, {'name': 'BaFeAgS3', 'entry_id': 1837608, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8358896686733459}, {'name': 'CaFeAgS3', 'entry_id': 1350935, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.724368360756679}, {'name': 'Cd2FeAgS4', 'entry_id': 1769203, 'spacegroup': 'Pmn21', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.5404612154441786}, {'name': 'CsFeAgSe2S', 'entry_id': 1302259, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.329381606918893}, {'name': 'CsFeAgTe2S', 'entry_id': 1302261, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230022215530003}, {'name': 'CsFeAgSeS2', 'entry_id': 1302257, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.394618080921119}, {'name': 'CsFeAgTeS2', 'entry_id': 1302258, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.375250961476674}, {'name': 'CsFeAgS3', 'entry_id': 1254445, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.421604442423346}, {'name': 'EuFeAgS3', 'entry_id': 1351367, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.8263010490900117}, {'name': 'EuFeAgS3', 'entry_id': 1835838, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.894365074923345}, {'name': 'FeAgSO4F', 'entry_id': 1814880, 'spacegroup': 'P-1', 'ntypes': 5, 'band_gap': 2.112, 'delta_e': -1.6308562340717154}, {'name': 'FeAgGeS3', 'entry_id': 1351151, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.346873213256679}, {'name': 'FeAgSI', 'entry_id': 1816530, 'spacegroup': 'P212121', 'ntypes': 4, 'band_gap': 0.2469999999999999, 'delta_e': -0.1760090803604193}, {'name': 'InFeAgSe2S', 'entry_id': 1302727, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230209696085559}, {'name': 'InFeAgTe2S', 'entry_id': 1302729, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.0257937596966696}, {'name': 'InFeAgSeS2', 'entry_id': 1302725, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.298717356754453}, {'name': 'InFeAgTeS2', 'entry_id': 1302726, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.240144403976675}, {'name': 'InFeAgS3', 'entry_id': 1254670, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.357073833256679}, {'name': 'KFeAgSe2S', 'entry_id': 1301323, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.332664887752227}, {'name': 'KFeAgTe2S', 'entry_id': 1301325, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.230393202196669}, {'name': 'KFeAgSeS2', 'entry_id': 1301321, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.398313917587786}, {'name': 'KFeAgTeS2', 'entry_id': 1301322, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.378438938143341}, {'name': 'KFeAgS3', 'entry_id': 1253995, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.431521720756678}, {'name': 'LiFeAgSe2S', 'entry_id': 1300387, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.298460757752226}, {'name': 'LiFeAgTe2S', 'entry_id': 1300389, 'spacegroup': 'C2/m', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.247503348863336}, {'name': 'LiFeAgSeS2', 'entry_id': 1300385, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.383124760087786}, {'name': 'LiFeAgTeS2', 'entry_id': 1300386, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.340523681476675}, {'name': 'LiFeAgS3', 'entry_id': 1253545, 'spacegroup': 'C2/m', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.423306621590012}, {'name': 'MgFeAgS3', 'entry_id': 1350863, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.50049405561779}, {'name': 'NaFeAgSe2S', 'entry_id': 1300855, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.2847245287275}, {'name': 'NaFeAgTe2S', 'entry_id': 1300857, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.210253226505277}, {'name': 'NaFeAgSeS2', 'entry_id': 1300853, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.369777656896394}, {'name': 'NaFeAgTeS2', 'entry_id': 1300854, 'spacegroup': 'Cmcm', 'ntypes': 5, 'band_gap': 0.0, 'delta_e': -0.355511549951949}, {'name': 'NaFeAgS3', 'entry_id': 1253770, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.409664657565287}, {'name': 'FeAgSO', 'entry_id': 1023501, 'spacegroup': 'Cmc21', 'ntypes': 4, 'band_gap': 0.206, 'delta_e': -0.492758781451588}, {'name': 'FeAgSO', 'entry_id': 1023725, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.571893011451588}, {'name': 'FeAgSO', 'entry_id': 1023780, 'spacegroup': 'Cmcm', 'ntypes': 4, 'band_gap': 0.225, 'delta_e': -0.563762981451589}, {'name': 'FeAgSO', 'entry_id': 1023446, 'spacegroup': 'P1', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.651989830201589}, {'name': 'FeAgSO', 'entry_id': 1036759, 'spacegroup': 'Pnma', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.673931222701588}, {'name': 'FeAgSO', 'entry_id': 1047500, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.313937075201588}, {'name': 'FeAgSO', 'entry_id': 1047617, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.240876586451589}, {'name': 'FeAgSO', 'entry_id': 1047842, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.0445543402015884}, {'name': 'FeAgSO', 'entry_id': 1047959, 'spacegroup': 'P4/nmm', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.794092405201589}, {'name': 'FeAgSO', 'entry_id': 1048184, 'spacegroup': 'Abm2', 'ntypes': 4, 'band_gap': 0.0, 'delta_e': -0.792194415826589}, {'name': 'FeAgSO', 'entry_id': 1048301, 'spacegroup': 'Pca21', 'ntypes': 4, 'band_gap': 0.401, 'delta_e': -0.526312738326588}, {'name': 'FeAgSO', 'entry_id': 1048526, 'spacegroup': 'P212121', 'ntypes': 4, 'band_gap': 0.201, 'delta_e': -0.678279640826589}]

In [18]:
len(get_data)

50

In [19]:
next=txt['links']['next']
while(next):
    repond=requests.get(next)
    txt=repond.json()
    for i in txt['data']:
        get_data.append(i)
    next=txt['links']['next'] 
    print(next)
print(len(get_data))

http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=100
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=150
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=200
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=250
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=300
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=350
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=400
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=450
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=500
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=550
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=600
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=650
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=700
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=750
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=800
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=850
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=900
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=950
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1000
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1050
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1100
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1150
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1200
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1250
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1300
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1350
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1400
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1450
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1500
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1550
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1600
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1650
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1700
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1750
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1800
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1850
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1900
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=1950
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=2000
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=2050
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=2100
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=2150
http://oqmd.org/oqmdapi/formationenergy?fields=name%2Centry_id%2Cspacegroup%2Cntypes%2Cband_gap%2Cdelta_e&filter=element_set%3DFe%2CS&limit=50&offset=2200
None
2244

In [20]:
oqmd_dict = {get_data[i]['entry_id']:[get_data[i]['name'],get_data[i]['spacegroup'],get_data[i]['ntypes'],get_data[i]['band_gap'],get_data[i]['delta_e']] for i in range(len(get_data))}
print(oqmd_dict)

{1742211: ['FeAgAsS3', 'Cc', 4, 0.0, -0.2716503474233451], 1969136: ['Fe2AgAuS4', 'P-6m2', 4, 0.0, -0.4033197854441788], 1351079: ['BaFeAgS3', 'Cmcm', 4, 0.0, -0.764094444090012], 1835815: ['BaFeAgS3', 'P21/m', 4, 0.0, -0.8278284815900125], 1837608: ['BaFeAgS3', 'Pnma', 4, 0.0, -0.8358896686733459], 1350935: ['CaFeAgS3', 'Cmcm', 4, 0.0, -0.724368360756679], 1769203: ['Cd2FeAgS4', 'Pmn21', 4, 0.0, -0.5404612154441786], 1302259: ['CsFeAgSe2S', 'Cmcm', 5, 0.0, -0.329381606918893], 1302261: ['CsFeAgTe2S', 'Cmcm', 5, 0.0, -0.230022215530003], 1302257: ['CsFeAgSeS2', 'Cmcm', 5, 0.0, -0.394618080921119], 1302258: ['CsFeAgTeS2', 'Cmcm', 5, 0.0, -0.375250961476674], 1254445: ['CsFeAgS3', 'Cmcm', 4, 0.0, -0.421604442423346], 1351367: ['EuFeAgS3', 'Cmcm', 4, 0.0, -0.8263010490900117], 1835838: ['EuFeAgS3', 'Pnma', 4, 0.0, -0.894365074923345], 1814880: ['FeAgSO4F', 'P-1', 5, 2.112, -1.6308562340717154], 1351151: ['FeAgGeS3', 'Cmcm', 4, 0.0, -0.346873213256679], 1816530: ['FeAgSI', 'P212121', 4, 0.2469999999999999, -0.1760090803604193], 1302727: ['InFeAgSe2S', 'Cmcm', 5, 0.0, -0.230209696085559], 1302729: ['InFeAgTe2S', 'Cmcm', 5, 0.0, -0.0257937596966696], 1302725: ['InFeAgSeS2', 'Cmcm', 5, 0.0, -0.298717356754453], 1302726: ['InFeAgTeS2', 'Cmcm', 5, 0.0, -0.240144403976675], 1254670: ['InFeAgS3', 'Cmcm', 4, 0.0, -0.357073833256679], 1301323: ['KFeAgSe2S', 'Cmcm', 5, 0.0, -0.332664887752227], 1301325: ['KFeAgTe2S', 'Cmcm', 5, 0.0, -0.230393202196669], 1301321: ['KFeAgSeS2', 'Cmcm', 5, 0.0, -0.398313917587786], 1301322: ['KFeAgTeS2', 'Cmcm', 5, 0.0, -0.378438938143341], 1253995: ['KFeAgS3', 'Cmcm', 4, 0.0, -0.431521720756678], 1300387: ['LiFeAgSe2S', 'Cmcm', 5, 0.0, -0.298460757752226], 1300389: ['LiFeAgTe2S', 'C2/m', 5, 0.0, -0.247503348863336], 1300385: ['LiFeAgSeS2', 'Cmcm', 5, 0.0, -0.383124760087786], 1300386: ['LiFeAgTeS2', 'Cmcm', 5, 0.0, -0.340523681476675], 1253545: ['LiFeAgS3', 'C2/m', 4, 0.0, -0.423306621590012], 1350863: ['MgFeAgS3', 'Cmcm', 4, 0.0, -0.50049405561779], 1300855: ['NaFeAgSe2S', 'Cmcm', 5, 0.0, -0.2847245287275], 1300857: ['NaFeAgTe2S', 'Cmcm', 5, 0.0, -0.210253226505277], 1300853: ['NaFeAgSeS2', 'Cmcm', 5, 0.0, -0.369777656896394], 1300854: ['NaFeAgTeS2', 'Cmcm', 5, 0.0, -0.355511549951949], 1253770: ['NaFeAgS3', 'Cmcm', 4, 0.0, -0.409664657565287], 1023501: ['FeAgSO', 'Cmc21', 4, 0.206, -0.492758781451588], 1023725: ['FeAgSO', 'Cmcm', 4, 0.0, -0.571893011451588], 1023780: ['FeAgSO', 'Cmcm', 4, 0.225, -0.563762981451589], 1023446: ['FeAgSO', 'P1', 4, 0.0, -0.651989830201589], 1036759: ['FeAgSO', 'Pnma', 4, 0.0, -0.673931222701588], 1047500: ['FeAgSO', 'P4/nmm', 4, 0.0, -0.313937075201588], 1047617: ['FeAgSO', 'P4/nmm', 4, 0.0, -0.240876586451589], 1047842: ['FeAgSO', 'P4/nmm', 4, 0.0, -0.0445543402015884], 1047959: ['FeAgSO', 'P4/nmm', 4, 0.0, -0.794092405201589], 1048184: ['FeAgSO', 'Abm2', 4, 0.0, -0.792194415826589], 1048301: ['FeAgSO', 'Pca21', 4, 0.401, -0.526312738326588], 1048526: ['FeAgSO', 'P212121', 4, 0.201, -0.678279640826589], 1048643: ['FeAgSO', 'P212121', 4, 0.406, -0.636003151451589], 1048868: ['FeAgSO', 'P4/nmm', 4, 0.0, -0.311510881451588], 1048985: ['FeAgSO', 'P4/nmm', 4, 0.0, -0.212025970201589], 1050011: ['FeAgSO', 'P21/c', 4, 0.0, -0.516209193639089], 1049894: ['FeAgSO', 'Pbca', 4, 0.0, -0.596899981139089], 1101126: ['FeAgSO', 'P4/nmm', 4, 0.0, -0.735225178951588], 1101317: ['FeAgSO', 'P21/c', 4, 0.0, -0.714376253951588], 1101507: ['FeAgSO', 'Pmc21', 4, 0.212, -0.687533520201589], 1103334: ['FeAgSO', 'Pca21', 4, 0.2, -0.516792940201588], 1110060: ['FeAgSO', 'P21', 4, 0.0, -0.653810085826589], 1270544: ['FeAgSO', 'Cmc21', 4, 0.212, -0.675017925201589], 1735807: ['Sr2FeAgSO3', 'P4/nmm', 5, 0.7549999999999994, -2.028880049070482], 1351295: ['FeAgPbS3', 'Cmcm', 4, 0.0, -0.316075666590012], 1301791: ['RbFeAgSe2S', 'Cmcm', 5, 0.0, -0.32631178358556], 1301793: ['RbFeAgTe2S', 'Cmcm', 5, 0.0, -0.224054615530003], 1301789: ['RbFeAgSeS2', 'Cmcm', 5, 0.0, -0.39287077592112], 1301790: ['RbFeAgTeS2', 'Cmcm', 5, 0.0, -0.371019615643341], 1254220: ['RbFeAgS3', 'Cmcm', 4, 0.0, -0.423401641590013], 1303195: ['TlFeAgSe2S', 'Cmcm', 5, 0.0, -0.128247296918893], 1303197: ['TlFeAgTe2S', 'Cmcm', 5, 0.0, -0.0225224913633362], 10121: ['FeAgS2', 'I-42d', 3, 0.0, -0.309199323881678], 99471: ['FeAgS2', 'I-42d', 3, 0.0, -0.309188512631678], 1773057: ['FeAgS2', 'Pna21', 3, 0.0, -0.29232147263167896], 1303193: ['TlFeAgSeS2', 'Cmcm', 5, 0.0, -0.240556057587786], 1303194: ['TlFeAgTeS2', 'Cmcm', 5, 0.0, -0.213994178976674], 1351223: ['FeAgSnS3', 'Cmcm', 4, 0.0, -0.394347351898546], 1351007: ['SrFeAgS3', 'Cmcm', 4, 0.0, -0.752565630756679], 1836818: ['SrFeAgS3', 'P21/m', 4, 0.0, -0.8393257674233455], 1836379: ['SrFeAgS3', 'Pnma', 4, 0.0, -0.8207509278400119], 1254895: ['TlFeAgS3', 'Cmcm', 4, 0.0, -0.253915751590013], 12470: ['Fe2AgS3', 'Cmca', 3, 0.0, -0.407933019090013], 21047: ['Fe2AgS3', 'P21/c', 3, 0.0, -0.413765360340013], 671448: ['Fe2AgS3', 'Cmca', 3, 0.0, -0.409521880756679], 1891598: ['Fe3AgS5', 'P6/mmm', 3, 0.0, -0.19067524195186536], 2060388: ['FeAg2H12C8S2N4O2', 'P21/c', 7, 3.077, -0.1420056619607283], 1771916: ['Cs2FeAg2S4', 'P42/mcm', 4, 0.0, -0.7089965612281589], 1277243: ['FeAg2GeS4', 'I-42m', 4, 0.38, -0.381575409506678], 1734388: ['FeAg2GeS4', 'Pmn21', 4, 0.355, -0.392340138256678], 2013371: ['FeAg2GeS4', 'I-4', 4, 0.0, -0.40511011200667824], 2013372: ['FeAg2GeS4', 'I-42m', 4, 0.3580000000000001, -0.3776451057566783], 1742452: ['FeAg2SI2', 'Cmc21', 4, 0.0, -0.26418788481166544], 1277232: ['InFeAg2S4', 'I-42m', 4, 0.0, -0.442698620131678], 1282287: ['KFeAg2S4', 'I-42m', 4, 0.0, -0.464521347006678], 1277283: ['FeSiAg2S4', 'I-42m', 4, 0.256, -0.479049425756678], 2024625: ['FeSiAg2S4', 'Pc', 4, 0.16000000000000014, -0.5013859045066784], 7801: ['FeAg2SnS4', 'I-42m', 4, 0.0, -0.409478315988078], 1953675: ['FeAg4S4', 'I-42m', 3, 0.0, -0.19924819289482482], 1261027: ['Ba2AlFeS6', 'Fm-3m', 4, 0.0, -1.17652517440801], 2009530: ['AlCdFeS4', 'P4122', 4, 0.0, -0.659023021936204], 2009528: ['AlCdFeS4', 'P4122', 4, 0.0, -0.6983099315790611], 2009536: ['AlCdFeS4', 'P4122', 4, 0.0, -0.8059090740790609], 27686: ['Ce3AlFeS7', 'P21', 4, 0.0, -1.73390175838279], 2009623: ['AlFeCoS4', 'P4122', 4, 0.0, -0.7703977672933472], 2009624: ['AlFeCoS4', 'P4122', 4, 0.0, -0.714005424436204], 2009625: ['AlFeCoS4', 'P4122', 4, 0.0, -0.7252695865790609], 2009993: ['AlFeCuS4', 'P4122', 4, 0.0, -0.7615537090790606], 27758: ['Dy3AlFeS7', 'P21', 4, 0.229, -1.72463301025779], 27785: ['Gd3AlFeS7', 'P21', 4, 0.0, -1.73560792796613], 2010306: ['AlFeGeS4', 'P4122', 4, 0.0, -0.6855827808647754], 2010307: ['AlFeGeS4', 'P4122', 4, 0.0, -0.6486089269362044], 2010309: ['AlFeGeS4', 'P4122', 4, 0.0, -0.6792708962219182], 27788: ['La3AlFeS7', 'P21', 4, 0.0, -1.8332519210911247], 2010338: ['MnAlFeS4', 'P4122', 4, 0.0, -0.8261082967637898], 2010341: ['MnAlFeS4', 'P4122', 4, 0.0, -0.779907463549504], 27792: ['Nd3AlFeS7', 'P21', 4, 0.0, -1.73580478442446], 27795: ['Pr3AlFeS7', 'P21', 4, 0.0, -1.73554206463279], 1838089: ['RbAlFeS3', 'Cmcm', 4, 0.0, -0.9805618170066784], 1848143: ['RbAlFeS3', 'P21/m', 4, 0.0, -1.0265760503400116], 27797: ['Sm3AlFeS7', 'P21', 4, 0.0, -1.73540148004946], 27798: ['Tb3AlFeS7', 'P21', 4, 0.0, -1.56656861184113], 27799: ['Y3AlFeS7', 'P21', 4, 0.0, -1.72231413359112], 1283452: ['AlFe2S4', 'Fd-3m', 3, 0.0, -0.694556655864776], 2010294: ['AlFe2S4', 'P4122', 3, 0.0, -0.7391669305076333], 2010295: ['AlFe2S4', 'P4122', 3, 0.0, -0.6943691072933476], 2010296: ['AlFe2S4', 'P4122', 3, 0.0, -0.7392151855076331], 1859406: ['Al2FeSe3S', 'P1', 4, 0.0, -0.7119190020019082], 27796: ['Al2FeS4', 'R3m', 3, 0.0, -0.945904069436205], 1278094: ['Al2FeS4', 'Pnma', 3, 0.0, -0.917873186936204], 1283420: ['Al2FeS4', 'Fd-3m', 3, 0.0, -0.997527177293347], 1737019: ['Al2FeS4', 'I-4', 3, 0.0, -0.981609888007633], 1261057: ['Ba2FeAsS6', 'Fm-3m', 4, 0.0, -0.979033009908014], 1261239: ['Ba2FeAsS6', 'Fm-3m', 4, 0.0, -0.978987049908014], 1765504: ['Fe3AsS4Br', 'Cmc21', 4, 0.0, -0.33361957094103034], 1765481: ['Fe3AsS4Cl', 'P63mc', 4, 0.0, -0.37028853296361713], 3281: ['FeAsS', 'P21/c', 3, 0.746, -0.549956371337787], 3280: ['FeAsS', 'P21/c', 3, 0.837000000000001, -0.549956636337786], 57495: ['FeAsS', 'P21/c', 3, 0.835999999999999, -0.550181532171119], 1551155: ['FeAsS', 'Pmn21', 3, 0.0, -0.4781371180044521], 1551156: ['FeAsS', 'Pmn21', 3, 0.0, -0.4776083613377864], 1551142: ['FeAsS', 'P2/m', 3, 0.0, -0.41694241300445256], 1556651: ['FeAsS', 'Pmn21', 3, 0.0, -0.479970419671119], 1556652: ['FeAsS', 'Pmn21', 3, 0.0, -0.47937624633778597], 1556644: ['FeAsS', 'P2/m', 3, 0.0, -0.4175788613377864], 1551157: ['Fe2AsS3', 'Pm', 3, 0.0, -0.567261039506679], 1556653: ['Fe2AsS3', 'Pm', 3, 0.0, -0.5667875345066792], 1748626: ['Fe2As2S2O3', 'I4/mmm', 4, 0.0, -0.7472194691657177], 1551137: ['Fe2As3S', 'Pm', 3, 0.0, -0.35765390150222603], 1556641: ['Fe2As3S', 'Pm', 3, 0.0, -0.3578514598355594], 1351103: ['BaFeAuS3', 'Cmcm', 4, 0.0, -0.708067812006679], 1836055: ['BaFeAuS3', 'Pnma', 4, 0.0, -0.783635289506679], 1261073: ['Ba2FeAuS6', 'Fm-3m', 4, 0.0, -0.889061713408015], 1350959: ['CaFeAuS3', 'Cmcm', 4, 0.0, -0.740367119506679], 1302415: ['CsFeAuSe2S', 'Cmcm', 5, 0.0, -0.296230664835559], 1302417: ['CsFeTe2AuS', 'Cmcm', 5, 0.0, -0.207804805946669], 1302413: ['CsFeAuSeS2', 'Cmcm', 5, 0.0, -0.384751466337786], 1302414: ['CsFeTeAuS2', 'Cmcm', 5, 0.0, -0.376693141060007], 1254520: ['CsFeAuS3', 'Cmcm', 4, 0.0, -0.388594075340012], 1351391: ['EuFeAuS3', 'Cmcm', 4, 0.0, -0.768578812006679], 1836794: ['EuFeAuS3', 'Pnma', 4, 0.0, -0.871782461173345], 1351175: ['FeGeAuS3', 'Cmcm', 4, 0.0, -0.341551417006679], 1302883: ['InFeAuSe2S', 'Cmcm', 5, 0.0, -0.238488631502226], 1302885: ['InFeTe2AuS', 'Cmcm', 5, 0.0, -0.0995387126133362], 1302881: ['InFeAuSeS2', 'Cmcm', 5, 0.0, -0.295467196337786], 1302882: ['InFeTeAuS2', 'Cmcm', 5, 0.0, -0.23795996439334], 1254745: ['InFeAuS3', 'Cmcm', 4, 0.0, -0.364257718673346], 1301479: ['KFeAuSe2S', 'Cmcm', 5, 0.0, -0.298572634002226], 1301481: ['KFeTe2AuS', 'Cmcm', 5, 0.0, -0.207631230113336], 1301477: ['KFeAuSeS2', 'Cmcm', 5, 0.0, -0.412049548837786], 1301478: ['KFeTeAuS2', 'Cmcm', 5, 0.0, -0.39591364939334], 1254070: ['KFeAuS3', 'Cmcm', 4, 0.0, -0.416335002006678], 1300543: ['LiFeAuSe2S', 'Cmcm', 5, 0.0, -0.309573281502226], 1300545: ['LiFeTe2AuS', 'Cmcm', 5, 0.0, -0.165936563446669], 1300541: ['LiFeAuSeS2', 'Cmcm', 5, 0.0, -0.426214433837786], 1300542: ['LiFeTeAuS2', 'Cmcm', 5, 0.0, -0.396292046060008], 1253620: ['LiFeAuS3', 'Cmcm', 4, 0.0, -0.453761932006679], 1350887: ['MgFeAuS3', 'Cmcm', 4, 0.0, -0.560019925201123], 1301011: ['NaFeAuSe2S', 'Cmcm', 5, 0.0, -0.283038351644168], 1301013: ['NaFeTe2AuS', 'Cmcm', 5, 0.0, -0.182087714421944], 1301009: ['NaFeAuSeS2', 'Cmcm', 5, 0.0, -0.41474379981306], 1301010: ['NaFeTeAuS2', 'Cmcm', 5, 0.0, -0.397924091201949], 1253845: ['NaFeAuS3', 'Cmcm', 4, 0.0, -0.429968808815287], 1101127: ['FeAuSO', 'P4/nmm', 4, 0.0, -0.353857939576589], 1101318: ['FeAuSO', 'P21/c', 4, 0.0, -0.579094455826588], 1101508: ['FeAuSO', 'Pmc21', 4, 0.0, -0.507295173326589], 1103335: ['FeAuSO', 'Pca21', 4, 0.302, -0.436931506451589], 1110061: ['FeAuSO', 'P21', 4, 0.0, -0.679641817076589], 1735808: ['Sr2FeAuSO3', 'P4/nmm', 5, 0.30100000000000016, -1.9559209200079817], 1351319: ['FePbAuS3', 'Cmcm', 4, 0.0, -0.324252027840012], 1301947: ['RbFeAuSe2S', 'Cmcm', 5, 0.0, -0.292966364002226], 1301949: ['RbFeTe2AuS', 'Cmcm', 5, 0.0, -0.201903074280002], 1301945: ['RbFeAuSeS2', 'Cmcm', 5, 0.0, -0.392097881337785], 1301946: ['RbFeTeAuS2', 'Cmcm', 5, 0.0, -0.383071704393341], 1254295: ['RbFeAuS3', 'Cmcm', 4, 0.0, -0.402539782840012], 1303351: ['TlFeAuSe2S', 'Cmcm', 5, 0.0, -0.124804509002226], 1303353: ['TlFeTe2AuS', 'Cmcm', 5, 0.0, -0.067960051780003], 1440274: ['FeAuS2', 'R-3m', 3, 0.0, -0.417906007006678], 1303349: ['TlFeAuSeS2', 'Cmcm', 5, 0.0, -0.235150673004452], 1303350: ['TlFeTeAuS2', 'Cmcm', 5, 0.0, -0.221641262726674], 1351247: ['FeSnAuS3', 'Cmcm', 4, 0.0, -0.40105986148188], 1351031: ['SrFeAuS3', 'Cmcm', 4, 0.0, -0.695267237006679], 1254970: ['TlFeAuS3', 'Cmcm', 4, 0.0, -0.238405782006679], 1891717: ['Fe3AuS5', 'P6/mmm', 3, 0.0, -0.10715388778519891], 1909023: ['CrFeAu2S4', 'P-3m1', 4, 0.0, -0.5155975295066781], 1908811: ['GaFeAu2S4', 'P-3m1', 4, 0.0, -0.44448521263167784], 1953679: ['FeAu4S4', 'I-42m', 3, 0.0, -0.005488718450380582], 1760011: ['FeBS3', 'P21/c', 3, 0.0, -0.32991756490801405], 1849319: ['BaCaFeS3', 'Cmcm', 4, 0.0, -1.6201925161733446], 1267409: ['BaCdFeS3', 'Cmcm', 4, 0.0, -1.05673970950668], 1267514: ['BaCdFeS3', 'Cmcm', 4, 0.0, -0.866619823673346], 646751: ['BaCe2FeS5', 'I4/mcm', 4, 0.0, -1.84893718889631], 1267418: ['BaFeCoS3', 'Cmcm', 4, 0.0, -0.927925314506679], 1267397: ['BaFeCoS3', 'Cmcm', 4, 0.0, -0.918353188673346], 1351055: ['BaFeCuS3', 'Cmcm', 4, 0.0, -0.924354967006679], 1836909: ['BaFeCuS3', 'Pnma', 4, 0.0, -0.9329080107566785], 1267412: ['BaEuFeS3', 'Cmcm', 4, 0.0, -1.67609396700668], 1267538: ['BaEuFeS3', 'Cmcm', 4, 0.0, -1.36605033867335], 1670361: ['BaSrFe2S2OF2', 'I4mm', 6, 1.3800000000000003, -2.395903799888461], 1267406: ['BaFeHgS3', 'Cmcm', 4, 0.0, -0.841282927001057], 1267490: ['BaFeHgS3', 'Cmcm', 4, 0.0, -0.721143427001056], 646750: ['BaLa2FeS5', 'I4/mcm', 4, 0.0, -1.93541682556298], 1267370: ['BaMnFeS3', 'Cmcm', 4, 0.0, -0.917196651805529], 1267391: ['BaMnFeS3', 'Cmcm', 4, 0.0, -1.04670504930553], 646753: ['BaNd2FeS5', 'I4/mcm', 4, 0.0, -1.85187036500742], 1267400: ['BaFeNiS3', 'Cmcm', 4, 0.0, -0.905257244506679], 1267442: ['BaFeNiS3', 'Cmcm', 4, 0.0, -0.932799998673345], 1023429: ['BaFeSO', 'Cmc21', 4, 2.02, -1.85109851207659], 1023440: ['BaFeSO', 'Cmc21', 4, 1.921, -1.80150560332659], 1023719: ['BaFeSO', 'Cmcm', 4, 0.0, -1.30199977332659], 1023708: ['BaFeSO', 'Cmcm', 4, 0.635, -1.83115692832659], 1036639: ['BaFeSO', 'Pnma', 4, 1.85, -1.87574419707659], 1047473: ['BaFeSO', 'P4/nmm', 4, 0.257000000000001, -1.69526088207659], 1047499: ['BaFeSO', 'P4/nmm', 4, 0.381, -1.69743887582659], 1047815: ['BaFeSO', 'P4/nmm', 4, 0.0, -1.55542115082659], 1047841: ['BaFeSO', 'P4/nmm', 4, 0.0, -1.12987190582659], 1048157: ['BaFeSO', 'Pca21', 4, 1.853, -1.77627682770159], 1048183: ['BaFeSO', 'Pca21', 4, 1.849, -1.82424801457659], 1048525: ['BaFeSO', 'P212121', 4, 1.598, -1.66933037770159], 1048841: ['BaFeSO', 'P4/nmm', 4, 0.0, -1.48305734582659], 1048499: ['BaFeSO', 'P212121', 4, 2.079, -1.64593506957659], 1049893: ['BaFeSO', 'Pbca', 4, 1.836, -1.87309627488909], 1270328: ['BaFeSO', 'Cmc21', 4, 1.763, -1.87526916957659], 1048867: ['BaFeSO', 'P4/nmm', 4, 0.711, -1.46982650207659], 1409385: ['BaFeSO', 'P63mc', 4, 0.0, -1.66930571332659], 1049867: ['BaFeSO', 'Pbca', 4, 0.0, -1.7929485036390886], 646752: ['BaPr2FeS5', 'I4/mcm', 4, 0.0, -1.85171554722964], 1280816: ['BaFeS2', 'Pnma', 3, 0.0, -1.29489455825668], 1556745: ['BaFeS2', 'Pmm2', 3, 0.0, -1.1478883870066783], 1751216: ['BaFeS2', 'Cmcm', 3, 0.0, -1.2894480882566786], 1812193: ['BaFeS2', 'Pmc21', 3, 0.0, -1.2617730482566785], 1814179: ['BaFeS2', 'P21/c', 3, 0.3650000000000002, -1.159493047006678], 1261256: ['BaFeS3', 'Pm-3m', 3, 0.0, -1.03224975240801], 1733149: ['BaFeS3', 'P63/mmc', 3, 0.0, -1.1741182944080144], 1758737: ['BaFeS3', 'P21/m', 3, 0.0, -1.0450504174080144], 1267403: ['BaZnFeS3', 'Cmcm', 4, 0.0, -1.03670464200668], 1267466: ['BaZnFeS3', 'Cmcm', 4, 0.0, -0.977094959506679], 646754: ['BaSm2FeS5', 'I4/mcm', 4, 0.0, -1.84893895445186], 1786316: ['BaGdFe2S5', 'Pmma', 4, 0.0, -1.284525794729642], 2024893: ['BaFe2S2O', 'Pmmn', 4, 1.5100000000000002, -1.4974007634556568], 3395: ['BaFe2S3', 'Cmcm', 3, 0.0, -1.12558272867335], 1267394: ['BaFe2S3', 'Cmcm', 3, 0.0, -0.920727050340012], 2019443: ['BaFe2S4', 'I4/m', 3, 0.0, -1.0309706237219183], 642711: ['Ba2FeBiS5', 'Pnma', 4, 0.725, -1.33114788611853], 1261117: ['Ba2FeBiS6', 'Fm-3m', 4, 0.0, -1.00943098890801], 1751384: ['Ba2Fe2S2Cl2O', 'I4/mmm', 5, 1.262, -1.771144551330243], 1261185: ['Ba2FeCoS6', 'Fm-3m', 4, 0.0, -0.971954885408014], 1261240: ['Ba2FeCoS6', 'Fm-3m', 4, 0.0, -0.971397309408015], 1261238: ['Ba2CrFeS6', 'Fm-3m', 4, 0.0, -1.11800221040801], 1261196: ['Ba2CrFeS6', 'Fm-3m', 4, 0.0, -1.10498537040801], 1751108: ['Ba2FeCuSO3', 'P4/nmm', 5, 0.7510000000000003, -2.015652890218858], 1261230: ['Ba2FeCuS6', 'Fm-3m', 4, 0.0, -0.956203910408015], 1670360: ['Ba2Fe2SeSOF2', 'I4mm', 6, 1.4100000000000001, -2.3410382894425323], 23573: ['Ba2Fe2S2OF2', 'I4/mmm', 5, 1.393, -2.39063828099957], 1873934: ['Ba2Fe2S2OF2', 'I4mm', 5, 1.505, -2.3929359676662396], 1261261: ['Ba2GaFeS6', 'Fm-3m', 4, 0.0, -1.05689520390801], 1261285: ['Ba2FeGeS6', 'Fm-3m', 4, 0.0, -1.01329760790801], 1261250: ['Ba2HfFeS6', 'Fm-3m', 4, 0.0, -1.47848863090801], 1261353: ['Ba2InFeS6', 'Fm-3m', 4, 0.0, -1.04689150040801], 1261241: ['Ba2FeIrS6', 'Fm-3m', 4, 0.0, -0.954614616408014], 1261422: ['Ba2MgFeS6', 'Fm-3m', 4, 0.0, -1.18407497732468], 1261251: ['Ba2MnFeS6', 'Fm-3m', 4, 0.0, -1.13530942978732], 1261242: ['Ba2FeMoS6', 'Fm-3m', 4, 0.0, -1.12918472740801], 1261252: ['Ba2NbFeS6', 'Fm-3m', 4, 0.0, -1.32738406540801], 1429860: ['Ba2NbFeS6', 'Fm-3m', 4, 0.0, -1.31029773540801], 1451950: ['Ba2NbFeS6', 'P-31c', 4, 0.0, -1.2885666399080145], 1708282: ['Ba2FeSO6', 'I4/mmm', 4, 0.0, -1.9233961747700121], 1709004: ['Ba2FeSO6', 'Fm-3m', 4, 0.0, -1.9234485377700126], 1725375: ['Ba2FeSO6', 'I4/m', 4, 1.1579999999999995, -1.9905895087700123], 1261243: ['Ba2FeOsS6', 'Fm-3m', 4, 0.0, -0.936158656408015], 1895942: ['Ba2FeOsS6', 'P-1', 4, 0.0, -0.9729625614080142], 1261244: ['Ba2FePtS6', 'Fm-3m', 4, 0.0, -0.962568721408015], 1261606: ['Ba2FePtS6', 'Fm-3m', 4, 0.0, -0.962705723408014], 1261245: ['Ba2FeReS6', 'Fm-3m', 4, 0.0, -1.01523992390801], 1429858: ['Ba2FeReS6', 'Fm-3m', 4, 0.0, -1.02847975190801], 1261246: ['Ba2FeRhS6', 'Fm-3m', 4, 0.0, -0.982035124408014], 1838567: ['Ba2FeS3', 'Pnma', 3, 0.0, -1.6137090590900118], 2050390: ['Ba2FeS3', 'Pnma', 3, 0.0, -1.6133462265900118], 2050391: ['Ba2FeS3', 'Pnma', 3, 0.0, -1.6258881290900125], 1280028: ['Ba2FeS4', 'I4/mmm', 3, 0.0, -1.4012284794362], 642710: ['Ba2FeSbS5', 'Pnma', 4, 0.599, -1.31634349361853], 1429861: ['Ba2TaFeS6', 'Fm-3m', 4, 0.0, -1.36137468840801], 1261248: ['Ba2FeTcS6', 'Fm-3m', 4, 0.0, -1.03775150190801], 1261254: ['Ba2TiFeS6', 'Fm-3m', 4, 0.0, -1.38319208478664], 1261255: ['Ba2VFeS6', 'Fm-3m', 4, 0.0, -1.21727673340801], 1261249: ['Ba2FeWS6', 'Fm-3m', 4, 0.0, -1.14032172640801], 1429859: ['Ba2FeWS6', 'Fm-3m', 4, 0.0, -1.16338815940801], 2049409: ['Ba3FeS4Br', 'Pnma', 4, 0.6019999999999999, -1.820896795107696], 1667: ['Ba3FeS5', 'Pnma', 3, 0.0, -1.64717274417409], 1770228: ['Ba3FeS5', 'I4/mcm', 3, 0.0, -1.6198698238963098], 2047875: ['Ba3UFeS6', 'P-3c1', 4, 0.0, -1.7637865084012252], 1347720: ['Ba3Fe2S6', 'C2/c', 3, 0.0, -1.45720687446183], 2064163: ['Ba4Ga2FeS6F4', 'Pnma', 5, 0.488, -2.318101172976739], 113968: ['Ba4Fe3S6F4', 'Pnma', 4, 0.0, -2.1599709988590923], 21985: ['Ba4Fe2S4I5', 'I4/m', 4, 0.243, -1.57898073854633], 37135: ['Ba5Fe4S11', 'Pmn21', 3, 0.0, -1.3615236202073462], 2046866: ['Ba6Fe25S27', 'Pm-3m', 3, 0.0, -0.8171789180751834], 3397: ['Ba6Fe8S15', 'I4/m', 3, 0.0, -1.20567139690346], 39707: ['Ba7Fe6S14', 'C2/c', 3, 0.0, -1.41665926448841], 1838300: ['CsBeFeS3', 'Cmcm', 4, 0.0, -0.8616034295066791], 1837930: ['KBeFeS3', 'Cmcm', 4, 0.0, -0.8916300603400119], 1047400: ['BeFeSO', 'P4/nmm', 4, 0.0, -0.495054145826588], 1047496: ['BeFeSO', 'P4/nmm', 4, 0.0, -0.745955194973028], 1047742: ['BeFeSO', 'P4/nmm', 4, 0.0, -0.804033644576588], 1047838: ['BeFeSO', 'P4/nmm', 4, 0.0, -1.31613900207659], 1048084: ['BeFeSO', 'Pca21', 4, 0.542, -1.64203464082659], 1048180: ['BeFeSO', 'Pca21', 4, 1.884, -1.44836653207659], 1048426: ['BeFeSO', 'P212121', 4, 1.862, -1.50896878645159], 1048522: ['BeFeSO', 'P212121', 4, 2.782, -1.44695124207659], 1048768: ['BeFeSO', 'P4/nmm', 4, 0.0, -0.410050214576588], 1048864: ['BeFeSO', 'P4/nmm', 4, 0.0, -0.945014863326588], 1049890: ['BeFeSO', 'Pbca', 4, 1.541, -1.30615667582659], 1049794: ['BeFeSO', 'Pbca', 4, 1.836, -1.50698673520159], 1838244: ['RbBeFeS3', 'Cmcm', 4, 0.0

In [21]:
import pandas as pd
df=pd.DataFrame.from_dict(oqmd_dict,orient="index")
df.head()

                 0      1  2    3         4
1742211   FeAgAsS3     Cc  4  0.0 -0.271650
1969136  Fe2AgAuS4  P-6m2  4  0.0 -0.403320
1351079   BaFeAgS3   Cmcm  4  0.0 -0.764094
1835815   BaFeAgS3  P21/m  4  0.0 -0.827828
1837608   BaFeAgS3   Pnma  4  0.0 -0.835890